vich_uploader:
    db_driver: orm

    mappings:
        evenements:
            uri_prefix: /images/evenements
            upload_destination: "%kernel.project_dir%/public/images/evenements"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        avatars:
            uri_prefix: /images/avatars
            upload_destination: "%kernel.project_dir%/public/images/avatars"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
